
title: CSCI-UA 480 (Algorithmic Problem Solving)
short_title: APS
description: "Course website for CSCI-UA 480 (Algorithmic Problem Solving) course."

baseurl: "/aps_f21" # the subpath of your site, e.g. /blog
#url: "https://joannakl.github.io/aps_s21" # the base hostname & protocol for your site, e.g. http://example.com

email_etiquette: "email_etiquette.md"
info: "info.md"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CSCI-UA 480"
course_name: "Algorithmic Problem Solving"
course_section: "52"
course_semester: "Fall 2021"
course_time: "Mondays and Wednesdays 9:30am - 10:45pm, (in person, classroom assignment by CAS, check your ALBERT schedule before the last day of classes)<br>"


current_course1_title: "CSCI 102 sec. 5"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs102_f21/"
current_course2_title: "CSCI 480 sec. 521 (APS)"
current_course2_link: "https://cs.nyu.edu/~joannakl/aps_f21/"
current_course3_title: ""
current_course3_link: ""


recitation_section1: "523"
recitation_time1:  "Thursdays 9:30-10:45AM, (in person)"
recitation_section2: "524"
recitation_time2:  "Thursdays 9:30-10:45AM, (online)"

recitation_instructor1_full: "???"
recitation_instructor1_name: "???"
recitation_instructor2_full: "???"
recitation_instructor2_name: "???"

tutor_full: "TBD"
tutor_name: ""

instructor_office_hours: "TBD,
(or you can schedule an appointment if these times do not work for you)"
instructor_office_hours_location: "Zoom (check NYU Classes for links)"

recitation1_office_hours: "TBD"
recitation1_office_hours_location: "TBD"

tutor_hours: "TBD"
tutor_hours_location: ""

midterm_exam_date: "TBD"
final_exam_date: "TBD "
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

ed_site: "https://us.edstem.org/"
ed_signup: "https://edstem.org/us/join/KgZ6kA"
gradescope_site: "https://gradescope.com/"
polleverywhere_guide: "https://blog.polleverywhere.com/students-poll-everywhere-101/"


book_opt_1: "Competitive Programming, "
book_opt_1_author: "Steven Halim, Felix Halim,  "
book_opt_1_edition: "3rd edition, "
book_opt_1_link: "https://cpbook.net/"
book_opt_1_note: "optional"
book_opt_1_image: "https://cpbook.net/img/cp3.png"


book_opt_2: "Programming challenges : the programming contest training manual"
book_opt_2_author: "Steven S. Skiena, Miguel A Revilla, "
book_opt_2_edition: ""
book_opt_2_link: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph004338804&context=L&vid=NYU&search_scope=all&tab=all&lang=en_US"
book_opt_2_note: "accessible through NYU Libraries"
book_opt_2_image: "https://media.springernature.com/w306/springer-static/cover-hires/book/978-0-387-22081-9"


book_opt_3: "Guide to competitive programming : learning and improving algorithms through contests, "
book_opt_3_author: "Antti Laaksonen, "
book_opt_3_edition: ""
book_opt_3_link: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph006481511&context=L&vid=NYU&search_scope=all&isFrbr=true&tab=all&lang=en_US"
book_opt_3_note: "accessible through NYU Libraries"
book_opt_3_image: "https://media.springernature.com/w306/springer-static/cover-hires/book/978-3-319-72547-5"


book_opt_4: "Principles of Algorithmic Problem Solving, "
book_opt_4_author: "Johan Sannemo, "
book_opt_4_edition: ""
book_opt_4_link: "http://www.csc.kth.se/~jsannemo/slask/main.pdf"
book_opt_4_note: "preliminary draft of the book, available through the author's site "
book_opt_4_image: ""


book_opt_5: "Algorithmic problem solving, "
book_opt_5_author: "Roland C. Backhouse, "
book_opt_5_edition: "2011"
book_opt_5_link: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph005560996&context=L&vid=NYU&search_scope=all&tab=all&lang=en_US"
book_opt_5_note: "accessible through NYU Librarires"
book_opt_5_image: "https://media.wiley.com/product_data/coverImage300/34/04706845/0470684534.jpg"
