
title: CSCI-UA 480 (Algorithmic Problem Solving)
description: "Course website for CSCI-UA 480 (Algorithmic Problem Solving) course."

baseurl: "/aps_s20" # the subpath of your site, e.g. /blog
url: "https://joannakl.github.io/aps_s20" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CSCI-UA 480"
course_name: "Algorithmic Problem Solving"
course_section: "004"
course_semester: "Spring 2019"
course_time: "<br>Tuesdays and Thursdays 12:30pm - 1:45pm, 12WP L120<br>"

recitation_section1: "005"
recitation_time1:  "Wednesdays 8:00-9:15AM, CIWW 101"

recitation_instructor1_full: "TBD"
recitation_instructor1_name: ""

tutor_full: "TBD"
tutor_name: ""

instructor_office_hours: "TBD,
(or you can schedule an appointment if these times do not work for you)"
instructor_office_hours_location: "423 CIWW"

recitation1_office_hours: "TBD"
recitation1_office_hours_location: "412 CIWW"

tutor_hours: "TBD"
tutor_hours_location: ""


current_course1_title: "CSCI 201 sec. 3"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs201_s20/"
current_course2_title: "CSCI 480 sec. 4 (APS)"
current_course2_link: "https://cs.nyu.edu/~joannakl/aps_s20/"
current_course3_title: "CSCI 480 sec. 10 (OSSD)"
current_course3_link: "https://cs.nyu.edu/~joannakl/ossd_s20/"

midterm_exam_date: "TBD"
final_exam_date: "TBD"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

piazza_site: https://piazza.com/nyu/spring2020/aps
gradescope_site: ""


book_opt_1: "Competitive Programming, "
book_opt_1_author: "Steven Halim, Felix Halim,  "
book_opt_1_edition: "3rd edition, "
book_opt_1_link: "https://cpbook.net/"
book_opt_1_note: "optional"
book_opt_1_image: "https://cpbook.net/img/cp3.png"


book_opt_2: "Programming challenges : the programming contest training manual"
book_opt_2_author: "Steven S. Skiena, Miguel A Revilla, "
book_opt_2_edition: ""
book_opt_2_link: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph004338804&context=L&vid=NYU&search_scope=all&tab=all&lang=en_US"
book_opt_2_note: "accessible through NYU Libraries"
book_opt_2_image: "https://media.springernature.com/w306/springer-static/cover-hires/book/978-0-387-22081-9"


book_opt_3: "Guide to competitive programming : learning and improving algorithms through contests, "
book_opt_3_author: "Antti Laaksonen, "
book_opt_3_edition: ""
book_opt_3_link: "https://media.springernature.com/w306/springer-static/cover-hires/book/978-3-319-72547-5"
book_opt_3_note: "accessible through NYU Libraries"
book_opt_3_image: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph006481511&context=L&vid=NYU&search_scope=all&isFrbr=true&tab=all&lang=en_US"


book_opt_4: "Principles of Algorithmic Problem Solving, "
book_opt_4_author: "Johan Sannemo, "
book_opt_4_edition: ""
book_opt_4_link: "http://www.csc.kth.se/~jsannemo/slask/main.pdf"
book_opt_4_note: "preliminary draft of the book, available through the author's site "
book_opt_4_image: ""


book_opt_5: "Algorithmic problem solving, "
book_opt_5_author: "Roland C. Backhouse, "
book_opt_5_edition: "2011"
book_opt_5_link: ""
book_opt_5_note: "accessible through NYU Librarires"
book_opt_5_image: "http://bobcat.library.nyu.edu/primo-explore/fulldisplay?docid=nyu_aleph005560996&context=L&vid=NYU&search_scope=all&tab=all&lang=en_US"
