
title: CSCI-UA 480 (Algorithmic Problem Solving)
description: "Course website for CSCI-UA 480 (Algorithmic Problem Solving) course."

baseurl: "/aps_s20" # the subpath of your site, e.g. /blog
url: "https://joannakl.github.io/aps_s20" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot

exclude:
  - Gemfile
  - Gemfile.lock



course_number: "CSCI-UA 480"
course_name: "Algorithmic Problem Solving"
course_section: "004"
course_semester: "Spring 2019"
course_time: "<br>Tuesdays and Thursdays 12:30pm - 1:45pm, 12WP L120<br>"

recitation_section1: "005"
recitation_time1:  "Wednesdays 8:00-9:15AM, CIWW 101"

recitation_instructor1_full: "TBD"
recitation_instructor1_name: ""

tutor_full: "TBD"
tutor_name: ""

instructor_office_hours: "TBD,
(or you can schedule an appointment if these times do not work for you)"
instructor_office_hours_location: "423 CIWW"

recitation1_office_hours: "TBD"
recitation1_office_hours_location: "412 CIWW"

tutor_hours: "TBD"
tutor_hours_location: ""


current_course1_title: "CSCI 201 sec. 3"
current_course1_link: "https://cs.nyu.edu/~joannakl/cs201_s20/"
current_course2_title: "CSCI 480 sec. 4 (APS)"
current_course2_link: "https://cs.nyu.edu/~joannakl/aps_s20/"
current_course3_title: "CSCI 480 sec. 10 (OSSD)"
current_course3_link: "https://cs.nyu.edu/~joannakl/ossd_s20/"

midterm_exam_date: "TBD"
final_exam_date: "TBD"
final_exams_link: "http://cs.nyu.edu/dynamic/courses/exams/"

piazza_site: https://piazza.com/nyu/spring2020/aps
gradescope_site: ""


book_opt_1: "Competitive Programming, "
book_opt_1_author: "Steven Halim, Felix Halim,  "
book_opt_1_edition: "3rd edition, "
book_opt_1_link: "https://cpbook.net/"
book_opt_1_note: "optional"
book_opt_1_image: "https://cpbook.net/img/cp3.png"


book_opt_2: "The Architecture of Open Source Applications, "
book_opt_2_author: "Amy Brown and Greg Wilson (editors), "
book_opt_2_edition: ""
book_opt_2_link: "http://www.aosabook.org/en/index.html"
book_opt_2_note: ""
book_opt_2_image: "http://www.aosabook.org/images/cover1.jpg"


book_opt_3: "Practical Open Source Software Exploration, "
book_opt_3_author: "Greg DeKoenigsberg, Chris Tyler, Karsten Wade, Max Spevack, Mel Chua, and Jeff Sheltren, "
book_opt_3_edition: ""
book_opt_3_link: "https://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html/"
book_opt_3_note: "(it hasn't been updated since 2010, but there is some good stuff in there)"
book_opt_3_image: ""




book_opt_4: "The Linux Command Line, "
book_opt_4_author: "William Shotts, "
book_opt_4_edition: ""
book_opt_4_link: "http://linuxcommand.org/tlcl.php"
book_opt_4_note: ""
book_opt_4_image: "http://linuxcommand.org/images/linuxcommandline.png"


book_opt_5: "ProGit, "
book_opt_5_author: "Scott Chacon and Ben Straub, "
book_opt_5_edition: "2nd edition"
book_opt_5_link: "https://git-scm.com/book/en/v2"
book_opt_5_note: ""
book_opt_5_image: "https://git-scm.com/images/progit2.png"
